spring.application.name=ocr-challenge

# File Upload Settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# OCR Settings
ocr.tessdata.path=${TESSDATA_PREFIX:/opt/homebrew/share/tessdata}
ocr.default.language=kor+eng
